### ISSUE TITLE
php7.0 support

### ISSUE THREAD

**Issue by bincani** [mithrandirii/php-zint#2]
trying to compile using /usr/include/php/7.0/php/Zend/zend_hash.h throws the following error.
```
zint.c:112:6: error: too many arguments to function 'zend_hash_get_current_data_ex'
zint.c:215:36: error: macro "RETVAL_STRING" passed 2 arguments, but takes just 1
```
